server:
  port: 8080
  servlet:
    context-path: /Restaurant_Admin_O_Lesyk
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/avada_slj_retl02?createDatabaseIfNotExist=true
    username: avada_slj_retl02
    password: GKoTVw1cVs
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org:
      springframework: info
      hibernate: error

upload:
  path: /D:/SpaceLab/restaurant_mvc_admin/uploads