name: Build & Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    name: Build and Deploy spring boot application
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.2.0
        env:
          MYSQL_ROOT_PASSWORD: GKoTVw1cVs
          MYSQL_DATABASE: avada_slj_retl02
          MYSQL_USER: avada_slj_retl02
          MYSQL_PASSWORD: GKoTVw1cVs
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 --port 3306 -uroot -pGKoTVw1cVs -e "SHOW DATABASES"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java 19
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '19'

      - name: Wait for MySQL
        run: sleep 15

      - name: Maven clean / install
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Tomcat Deploy
        run: curl -v -u robot:K4QU@mJ!djX4D8X2 -T /home/runner/work/restaurant_mvc_admin/restaurant_mvc_admin/target/Restaurant_Admin_O_Lesyk.war 'https://slj.avada-media-dev1.od.ua/manager/text/deploy?path=/Restaurant_Admin_O_Lesyk&update=true'
