name: Build & Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-deploy:
    name: Build and Deploy spring boot application
    runs-on: ubuntu-latest
    services:
      mysql-master:
        image: mysql:8.2.0
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: avada_slj_retl02
          MYSQL_ROOT_PASSWORD: GKoTVw1cVs
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 19
      - name: Grant privileges and flush
        run: |
          mysql -h 127.0.0.1 -u root -pGKoTVw1cVs -e "GRANT ALL PRIVILEGES ON avada_slj_retl02.* TO 'avada_slj_retl02'@'%' WITH GRANT OPTION;"
          mysql -h 127.0.0.1 -u root -pGKoTVw1cVs -e "FLUSH PRIVILEGES;"

      - name: Unit Tests
        env:
          DATABASE_NAME: avada_slj_retl02
          DATABASE_USERNAME: avada_slj_retl02
          DATABASE_PASSWORD: GKoTVw1cVs
          DATABASE_ENDPOINT: 127.0.0.1
        run: mvn -B test --file pom.xml

      - name: Build application
        run: |
          mvn clean
          mvn -B package --file pom.xml

      - name: Tomcat Deploy
        run: curl -v -u robot:K4QU@mJ!djX4D8X2 -T /home/runner/work/restaurant_mvc_admin/target/Restaurant_Admin_O_Lesyk.war 'https://slj.avada-media-dev1.od.ua/manager/text/deploy?path=/Restaurant_Admin_O_Lesyk&update=true'